import JSZip from 'jszip'
import type { Journey } from './journey-schema'

/**
 * Builds a complete, runnable Vite + React + React Router application from a
 * Journey and returns it as a ZIP Blob. Every journey step becomes its own
 * page file and route; shared GOV.UK components, styling, validation and
 * routing logic are emitted as real source files so the download runs with
 * `npm install && npm run dev`.
 */
export async function generateAppZip(journey: Journey): Promise<Blob> {
  const zip = new JSZip()
  const files = buildFiles(journey)
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content)
  }
  return zip.generateAsync({ type: 'blob' })
}

export function buildFiles(journey: Journey): Record<string, string> {
  const files: Record<string, string> = {}
  const serviceTitle = journey.title || 'GOV.UK service'

  files['package.json'] = PACKAGE_JSON
  files['README.md'] = readme(serviceTitle)
  files['.gitignore'] = GITIGNORE
  files['vite.config.js'] = VITE_CONFIG
  files['index.html'] = indexHtml(serviceTitle)
  files['public/favicon.svg'] = FAVICON_SVG

  files['src/main.jsx'] = MAIN_JSX
  files['src/App.jsx'] = appJsx(journey)
  files['src/store.jsx'] = STORE_JSX
  files['src/journey.json'] = JSON.stringify(journey, null, 2)
  files['src/lib/journey.js'] = JOURNEY_LIB
  files['src/styles/govuk.css'] = GOVUK_CSS

  files['src/components/Layout.jsx'] = LAYOUT_JSX
  files['src/components/BackLink.jsx'] = BACKLINK_JSX
  files['src/components/ErrorSummary.jsx'] = ERROR_SUMMARY_JSX
  files['src/components/JourneyPage.jsx'] = JOURNEY_PAGE_JSX

  journey.steps.forEach((_, i) => {
    const n = i + 1
    files[`src/pages/Page${n}.jsx`] =
      `import JourneyPage from '../components/JourneyPage.jsx'\n\n` +
      `export default function Page${n}() {\n  return <JourneyPage index={${i}} />\n}\n`
  })

  return files
}

/* ------------------------------------------------------------------ */
/* Dynamic files                                                       */
/* ------------------------------------------------------------------ */

function appJsx(journey: Journey): string {
  const imports = journey.steps
    .map((_, i) => `import Page${i + 1} from './pages/Page${i + 1}.jsx'`)
    .join('\n')
  const list = journey.steps.map((_, i) => `Page${i + 1}`).join(', ')

  return `import { Routes, Route } from 'react-router-dom'
import { FormProvider } from './store.jsx'
import { routePaths } from './lib/journey.js'
${imports}

const pages = [${list}]

export default function App() {
  return (
    <FormProvider>
      <Routes>
        {routePaths.map((path, i) => {
          const Page = pages[i]
          return <Route key={path} path={path} element={<Page />} />
        })}
        <Route path="*" element={<Page1 />} />
      </Routes>
    </FormProvider>
  )
}
`
}

function indexHtml(serviceTitle: string): string {
  return `<!doctype html>
<html lang="en" class="govuk-template">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <title>${escapeHtml(serviceTitle)}</title>
  </head>
  <body class="govuk-template__body">
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`
}

function readme(serviceTitle: string): string {
  return `# ${serviceTitle}

A complete GOV.UK-styled service prototype generated by **GDS Journey Builder**.
It is a Vite + React application that uses React Router to connect every page in
the journey, with client-side validation and shared accessible components.

## Requirements

- Node.js 18 or newer

## Setup

Install dependencies and start the development server:

    npm install
    npm run dev

Then open the local URL printed in the terminal (usually http://localhost:5173).

## Production build

    npm run build
    npm run preview

## Project structure

- index.html — app entry document
- src/main.jsx — React entry point and router setup
- src/App.jsx — route definitions, one route per journey step
- src/journey.json — the journey definition this app was generated from
- src/lib/journey.js — derived steps, route paths and field helpers
- src/store.jsx — form state shared across pages
- src/pages/ — one page component per journey step
- src/components/ — shared GOV.UK layout, back link, error summary and page renderer
- src/styles/govuk.css — GOV.UK styling
- public/ — static assets

## How navigation works

Pages are rendered in the same order as the journey. Each page validates its
required fields, shows an error summary when something is missing, and moves to
the next page on Continue. A Back link returns to the previous page. The
check-your-answers page lists earlier answers, and the confirmation page shows a
success panel.
`
}

/* ------------------------------------------------------------------ */
/* Static files                                                        */
/* ------------------------------------------------------------------ */

const PACKAGE_JSON = `{
  "name": "gds-journey-app",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.26.2"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "vite": "^5.4.8"
  }
}
`

const GITIGNORE = `node_modules
dist
.DS_Store
`

const VITE_CONFIG = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`

const FAVICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" fill="#0b0c0c" />
  <text x="16" y="21" font-family="Arial, sans-serif" font-size="14" font-weight="bold" fill="#ffffff" text-anchor="middle">G</text>
</svg>
`

const MAIN_JSX = `import React from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App.jsx'
import './styles/govuk.css'

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
)
`

const STORE_JSX = `import { createContext, useContext, useState } from 'react'

const FormContext = createContext(null)

export function FormProvider({ children }) {
  const [values, setValues] = useState({})
  const setValue = (key, value) => setValues((prev) => Object.assign({}, prev, { [key]: value }))
  return <FormContext.Provider value={{ values, setValue }}>{children}</FormContext.Provider>
}

export function useForm() {
  const ctx = useContext(FormContext)
  if (!ctx) throw new Error('useForm must be used within a FormProvider')
  return ctx
}
`

const JOURNEY_LIB = `import journey from '../journey.json'

export const steps = journey.steps
export const service = journey.title

export function slug(text) {
  return String(text == null ? '' : text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

export const routePaths = (function () {
  const seen = {}
  return steps.map(function (step, i) {
    let p
    if (i === 0) p = '/'
    else if (step.url && step.url.charAt(0) === '/') p = step.url
    else p = '/' + (slug(step.title) || 'page-' + (i + 1))
    if (seen[p]) p = p + '-' + i
    seen[p] = true
    return p
  })
})()

export function fieldKey(step, comp, i) {
  return (slug(comp.label) || comp.type + '-' + i) + '-' + step.id
}

export const FIELD_TYPES = ['text-input', 'textarea', 'radios', 'checkboxes', 'date-input', 'file-upload']
`

const LAYOUT_JSX = `import { service } from '../lib/journey.js'

export default function Layout({ children }) {
  return (
    <>
      <header className="govuk-header" role="banner">
        <div className="govuk-width-container govuk-header__container">
          <span className="govuk-header__logo">GOV.UK</span>
          <span className="govuk-header__service">{service}</span>
        </div>
      </header>
      <div className="govuk-width-container">
        <div className="govuk-phase-banner">
          <span className="govuk-phase-banner__tag">Beta</span>
          <span className="govuk-phase-banner__text">
            This is a new service — your feedback will help us to improve it.
          </span>
        </div>
        <main className="govuk-main-wrapper" id="main-content" role="main">
          {children}
        </main>
      </div>
      <footer className="govuk-footer" role="contentinfo">
        <div className="govuk-width-container">
          <p className="govuk-footer__text">Built with GOV.UK design principles.</p>
        </div>
      </footer>
    </>
  )
}
`

const BACKLINK_JSX = `import { useNavigate } from 'react-router-dom'

export default function BackLink({ to }) {
  const navigate = useNavigate()
  return (
    <a
      className="govuk-back-link"
      href="#"
      onClick={(e) => {
        e.preventDefault()
        navigate(to)
      }}
    >
      Back
    </a>
  )
}
`

const ERROR_SUMMARY_JSX = `export default function ErrorSummary({ errors }) {
  if (!errors || errors.length === 0) return null
  return (
    <div className="govuk-error-summary" role="alert" aria-labelledby="error-summary-title">
      <h2 className="govuk-error-summary__title" id="error-summary-title">
        There is a problem
      </h2>
      <div className="govuk-error-summary__body">
        <ul className="govuk-list govuk-error-summary__list">
          {errors.map((err) => (
            <li key={err.key}>
              <a href={'#' + err.key}>{err.message}</a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}
`

const JOURNEY_PAGE_JSX = `import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { steps, routePaths, fieldKey, FIELD_TYPES } from '../lib/journey.js'
import { useForm } from '../store.jsx'
import Layout from './Layout.jsx'
import BackLink from './BackLink.jsx'
import ErrorSummary from './ErrorSummary.jsx'

function isFieldEmpty(type, v) {
  if (type === 'checkboxes') return !Array.isArray(v) || v.length === 0
  if (type === 'date-input') return !v || !v.day || !v.month || !v.year
  return v === undefined || v === null || String(v).trim() === ''
}

function formatValue(type, v) {
  if (v === undefined || v === null || v === '') return 'Not provided'
  if (type === 'checkboxes') return Array.isArray(v) ? v.join(', ') : 'Not provided'
  if (type === 'date-input') return [v.day, v.month, v.year].filter(Boolean).join(' / ') || 'Not provided'
  return String(v)
}

export default function JourneyPage({ index }) {
  const step = steps[index]
  const navigate = useNavigate()
  const { values, setValue } = useForm()
  const [errors, setErrors] = useState([])

  const prevPath = index > 0 ? routePaths[index - 1] : null
  const nextPath = index < steps.length - 1 ? routePaths[index + 1] : null

  const enriched = step.components.map((c, i) =>
    Object.assign({}, c, { key: fieldKey(step, c, i), _index: i }),
  )
  const fields = enriched.filter((c) => FIELD_TYPES.indexOf(c.type) !== -1)
  const hasConfirmation = step.components.some((c) => c.type === 'confirmation')
  const buttonComp = step.components.find((c) => c.type === 'button')
  const actionLabel = buttonComp && buttonComp.label ? buttonComp.label : 'Continue'
  const isStart = !!buttonComp && /start/i.test(buttonComp.label || '')

  function handleSubmit(e) {
    e.preventDefault()
    const errs = fields
      .filter((f) => isFieldEmpty(f.type, values[f.key]))
      .map((f) => ({ key: f.key, message: (f.label || 'This field') + ' is required' }))
    setErrors(errs)
    if (errs.length > 0) {
      window.scrollTo(0, 0)
      return
    }
    if (nextPath) navigate(nextPath)
  }

  function toggleCheckbox(key, option) {
    const current = Array.isArray(values[key]) ? values[key] : []
    if (current.indexOf(option) === -1) setValue(key, current.concat(option))
    else setValue(key, current.filter((o) => o !== option))
  }

  function renderComponent(c) {
    const key = c.key
    const errored = errors.some((er) => er.key === key)
    const groupClass = 'govuk-form-group' + (errored ? ' govuk-form-group--error' : '')

    switch (c.type) {
      case 'paragraph':
        return (
          <p className="govuk-body" key={c._index}>
            {c.text}
          </p>
        )

      case 'text-input':
        return (
          <div className={groupClass} key={c._index}>
            <label className="govuk-label" htmlFor={key}>
              {c.label}
            </label>
            {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
            {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
            <input
              className="govuk-input"
              id={key}
              name={key}
              type="text"
              value={values[key] || ''}
              onChange={(e) => setValue(key, e.target.value)}
            />
          </div>
        )

      case 'textarea':
        return (
          <div className={groupClass} key={c._index}>
            <label className="govuk-label" htmlFor={key}>
              {c.label}
            </label>
            {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
            {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
            <textarea
              className="govuk-textarea"
              id={key}
              name={key}
              rows={5}
              value={values[key] || ''}
              onChange={(e) => setValue(key, e.target.value)}
            />
          </div>
        )

      case 'radios':
        return (
          <div className={groupClass} key={c._index}>
            <fieldset className="govuk-fieldset">
              <legend className="govuk-fieldset__legend">{c.label}</legend>
              {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
              {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
              <div className="govuk-radios">
                {(c.options || ['Yes', 'No']).map((opt, oi) => (
                  <div className="govuk-radios__item" key={oi}>
                    <input
                      className="govuk-radios__input"
                      id={key + '-' + oi}
                      name={key}
                      type="radio"
                      value={opt}
                      checked={values[key] === opt}
                      onChange={() => setValue(key, opt)}
                    />
                    <label className="govuk-label govuk-radios__label" htmlFor={key + '-' + oi}>
                      {opt}
                    </label>
                  </div>
                ))}
              </div>
            </fieldset>
          </div>
        )

      case 'checkboxes':
        return (
          <div className={groupClass} key={c._index}>
            <fieldset className="govuk-fieldset">
              <legend className="govuk-fieldset__legend">{c.label}</legend>
              {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
              {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
              <div className="govuk-checkboxes">
                {(c.options || []).map((opt, oi) => (
                  <div className="govuk-checkboxes__item" key={oi}>
                    <input
                      className="govuk-checkboxes__input"
                      id={key + '-' + oi}
                      name={key}
                      type="checkbox"
                      value={opt}
                      checked={Array.isArray(values[key]) && values[key].indexOf(opt) !== -1}
                      onChange={() => toggleCheckbox(key, opt)}
                    />
                    <label className="govuk-label govuk-checkboxes__label" htmlFor={key + '-' + oi}>
                      {opt}
                    </label>
                  </div>
                ))}
              </div>
            </fieldset>
          </div>
        )

      case 'date-input': {
        const dv = values[key] || {}
        return (
          <div className={groupClass} key={c._index}>
            <fieldset className="govuk-fieldset">
              <legend className="govuk-fieldset__legend">{c.label}</legend>
              {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
              {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
              <div className="govuk-date-input" id={key}>
                {['day', 'month', 'year'].map((part) => (
                  <div className="govuk-date-input__item" key={part}>
                    <label
                      className="govuk-label govuk-date-input__label"
                      htmlFor={key + '-' + part}
                    >
                      {part.charAt(0).toUpperCase() + part.slice(1)}
                    </label>
                    <input
                      className={
                        'govuk-input govuk-date-input__input ' +
                        (part === 'year' ? 'govuk-input--width-4' : 'govuk-input--width-2')
                      }
                      id={key + '-' + part}
                      name={key + '-' + part}
                      type="text"
                      inputMode="numeric"
                      value={dv[part] || ''}
                      onChange={(e) => setValue(key, Object.assign({}, dv, { [part]: e.target.value }))}
                    />
                  </div>
                ))}
              </div>
            </fieldset>
          </div>
        )
      }

      case 'file-upload':
        return (
          <div className={groupClass} key={c._index}>
            <label className="govuk-label" htmlFor={key}>
              {c.label}
            </label>
            {c.hint ? <div className="govuk-hint">{c.hint}</div> : null}
            {errored ? <p className="govuk-error-message">{c.label} is required</p> : null}
            <input
              className="govuk-file-upload"
              id={key}
              name={key}
              type="file"
              onChange={(e) =>
                setValue(key, e.target.files && e.target.files[0] ? e.target.files[0].name : '')
              }
            />
          </div>
        )

      case 'summary-list': {
        const rows = []
        steps.forEach((s, si) => {
          if (si >= index) return
          s.components.forEach((sc, sci) => {
            if (FIELD_TYPES.indexOf(sc.type) === -1) return
            const k = fieldKey(s, sc, sci)
            rows.push({
              label: sc.label || sc.type,
              value: formatValue(sc.type, values[k]),
              to: routePaths[si],
            })
          })
        })
        return (
          <dl className="govuk-summary-list" key={c._index}>
            {rows.length === 0 ? (
              <div className="govuk-summary-list__row">
                <dt className="govuk-summary-list__key">No answers yet</dt>
                <dd className="govuk-summary-list__value" />
                <dd className="govuk-summary-list__actions" />
              </div>
            ) : (
              rows.map((r, ri) => (
                <div className="govuk-summary-list__row" key={ri}>
                  <dt className="govuk-summary-list__key">{r.label}</dt>
                  <dd className="govuk-summary-list__value">{r.value}</dd>
                  <dd className="govuk-summary-list__actions">
                    <Link to={r.to}>Change</Link>
                  </dd>
                </div>
              ))
            )}
          </dl>
        )
      }

      case 'confirmation':
        return (
          <div className="govuk-panel govuk-panel--confirmation" key={c._index}>
            <h1 className="govuk-panel__title">{c.text || 'Application complete'}</h1>
          </div>
        )

      case 'button':
      default:
        return null
    }
  }

  return (
    <Layout>
      {prevPath ? <BackLink to={prevPath} /> : null}
      <ErrorSummary errors={errors} />
      {!hasConfirmation ? (
        <h1 className="govuk-heading-l">{step.heading || step.title}</h1>
      ) : null}
      {!hasConfirmation && step.description ? (
        <p className="govuk-body">{step.description}</p>
      ) : null}

      {hasConfirmation ? (
        <div>
          {enriched.map(renderComponent)}
          {step.description ? <p className="govuk-body">{step.description}</p> : null}
          {index > 0 ? (
            <p className="govuk-body">
              <Link to={routePaths[0]}>Return to the start</Link>
            </p>
          ) : null}
        </div>
      ) : (
        <form onSubmit={handleSubmit} noValidate>
          {enriched.map(renderComponent)}
          <button
            type="submit"
            className={'govuk-button' + (isStart ? ' govuk-button--start' : '')}
          >
            {actionLabel}
            {isStart ? (
              <svg
                className="govuk-button__start-icon"
                xmlns="http://www.w3.org/2000/svg"
                width="17.5"
                height="19"
                viewBox="0 0 33 40"
                aria-hidden="true"
                focusable="false"
              >
                <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
              </svg>
            ) : null}
          </button>
        </form>
      )}
    </Layout>
  )
}
`

const GOVUK_CSS = `:root {
  --govuk-black: #0b0c0c;
  --govuk-blue: #1d70b8;
  --govuk-green: #00703c;
  --govuk-green-dark: #002d18;
  --govuk-red: #d4351c;
  --govuk-yellow: #ffdd00;
  --govuk-grey: #505a5f;
  --govuk-light-grey: #f3f2f1;
  --govuk-mid-grey: #b1b4b6;
}

* {
  box-sizing: border-box;
}

html {
  background: #f3f2f1;
}

body {
  margin: 0;
  color: var(--govuk-black);
  background: #f3f2f1;
  font-family: arial, helvetica, sans-serif;
  font-size: 19px;
  line-height: 1.4;
  -webkit-font-smoothing: antialiased;
}

.govuk-width-container {
  max-width: 960px;
  margin: 0 auto;
  padding: 0 15px;
}

/* Header */
.govuk-header {
  background: var(--govuk-black);
  border-bottom: 10px solid var(--govuk-blue);
  color: #ffffff;
}

.govuk-header__container {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 10px;
  padding: 10px 15px;
}

.govuk-header__logo {
  font-weight: 700;
  font-size: 30px;
  letter-spacing: 0.5px;
  color: #ffffff;
}

.govuk-header__service {
  font-size: 19px;
  font-weight: 700;
  color: #ffffff;
}

/* Phase banner */
.govuk-phase-banner {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 0;
  border-bottom: 1px solid var(--govuk-mid-grey);
}

.govuk-phase-banner__tag {
  display: inline-block;
  padding: 3px 8px;
  background: var(--govuk-blue);
  color: #ffffff;
  font-size: 14px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 1px;
}

.govuk-phase-banner__text {
  font-size: 16px;
  color: var(--govuk-grey);
}

/* Main */
.govuk-main-wrapper {
  padding: 40px 0;
  min-height: 40vh;
}

/* Typography */
.govuk-heading-l {
  font-size: 36px;
  line-height: 1.1;
  font-weight: 700;
  margin: 0 0 30px;
}

.govuk-body {
  font-size: 19px;
  margin: 0 0 20px;
  max-width: 38em;
}

.govuk-list {
  padding-left: 20px;
}

a {
  color: var(--govuk-blue);
}

a:focus {
  outline: 3px solid transparent;
  background-color: var(--govuk-yellow);
  box-shadow: 0 -2px var(--govuk-yellow), 0 4px var(--govuk-black);
  color: var(--govuk-black);
  text-decoration: none;
}

/* Back link */
.govuk-back-link {
  display: inline-block;
  margin-bottom: 20px;
  font-size: 16px;
  color: var(--govuk-black);
}

.govuk-back-link::before {
  content: '';
  display: inline-block;
  width: 7px;
  height: 7px;
  margin-right: 6px;
  border: solid currentColor;
  border-width: 1px 1px 0 0;
  transform: rotate(-135deg);
  vertical-align: middle;
}

/* Form groups */
.govuk-form-group {
  margin-bottom: 30px;
  padding-left: 0;
}

.govuk-form-group--error {
  padding-left: 15px;
  border-left: 5px solid var(--govuk-red);
}

.govuk-label {
  display: block;
  font-size: 19px;
  font-weight: 700;
  margin-bottom: 5px;
}

.govuk-fieldset__legend {
  font-size: 19px;
  font-weight: 700;
  margin-bottom: 10px;
  padding: 0;
}

.govuk-fieldset {
  border: 0;
  margin: 0;
  padding: 0;
}

.govuk-hint {
  color: var(--govuk-grey);
  font-size: 19px;
  margin-bottom: 10px;
}

.govuk-error-message {
  color: var(--govuk-red);
  font-weight: 700;
  font-size: 19px;
  margin: 0 0 10px;
}

.govuk-input,
.govuk-textarea {
  width: 100%;
  max-width: 30em;
  padding: 5px 4px;
  font-size: 19px;
  font-family: inherit;
  border: 2px solid var(--govuk-black);
  border-radius: 0;
  background: #ffffff;
}

.govuk-textarea {
  max-width: 100%;
}

.govuk-input:focus,
.govuk-textarea:focus,
.govuk-radios__input:focus + .govuk-radios__label::before,
.govuk-checkboxes__input:focus + .govuk-checkboxes__label::before {
  outline: 3px solid var(--govuk-yellow);
  outline-offset: 0;
  box-shadow: inset 0 0 0 2px;
}

.govuk-input--width-2 {
  max-width: 3.6em;
}

.govuk-input--width-4 {
  max-width: 5.4em;
}

/* Radios & checkboxes */
.govuk-radios__item,
.govuk-checkboxes__item {
  position: relative;
  display: block;
  margin-bottom: 12px;
  padding-left: 44px;
  min-height: 40px;
}

.govuk-radios__input,
.govuk-checkboxes__input {
  position: absolute;
  left: 0;
  top: 0;
  width: 40px;
  height: 40px;
  margin: 0;
  opacity: 0;
  cursor: pointer;
  z-index: 1;
}

.govuk-radios__label,
.govuk-checkboxes__label {
  display: inline-block;
  padding: 8px 0;
  cursor: pointer;
  font-weight: 400;
}

.govuk-radios__label::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 40px;
  height: 40px;
  border: 2px solid var(--govuk-black);
  border-radius: 50%;
  background: #ffffff;
}

.govuk-radios__input:checked + .govuk-radios__label::after {
  content: '';
  position: absolute;
  left: 10px;
  top: 10px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: var(--govuk-black);
}

.govuk-checkboxes__label::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 40px;
  height: 40px;
  border: 2px solid var(--govuk-black);
  background: #ffffff;
}

.govuk-checkboxes__input:checked + .govuk-checkboxes__label::after {
  content: '';
  position: absolute;
  left: 10px;
  top: 15px;
  width: 18px;
  height: 8px;
  border: solid var(--govuk-black);
  border-width: 0 0 4px 4px;
  transform: rotate(-45deg);
}

/* Date input */
.govuk-date-input {
  display: flex;
  gap: 20px;
}

.govuk-date-input__item {
  display: flex;
  flex-direction: column;
}

.govuk-date-input__label {
  font-size: 16px;
  font-weight: 400;
  margin-bottom: 5px;
}

/* File upload */
.govuk-file-upload {
  font-size: 19px;
}

/* Buttons */
.govuk-button {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin-top: 10px;
  padding: 8px 15px 7px;
  border: 2px solid transparent;
  border-radius: 0;
  color: #ffffff;
  background: var(--govuk-green);
  box-shadow: 0 2px 0 var(--govuk-green-dark);
  font-size: 19px;
  font-family: inherit;
  font-weight: 400;
  cursor: pointer;
  -webkit-appearance: none;
}

.govuk-button:hover {
  background: #005a30;
}

.govuk-button:focus {
  outline: 3px solid transparent;
  background: var(--govuk-yellow);
  color: var(--govuk-black);
  box-shadow: 0 2px 0 var(--govuk-black);
}

.govuk-button--start {
  font-size: 24px;
  font-weight: 700;
  padding: 10px 20px;
}

.govuk-button__start-icon {
  margin-left: 6px;
}

/* Error summary */
.govuk-error-summary {
  padding: 20px;
  margin-bottom: 30px;
  border: 5px solid var(--govuk-red);
}

.govuk-error-summary__title {
  margin: 0 0 15px;
  font-size: 24px;
  font-weight: 700;
}

.govuk-error-summary__list {
  margin: 0;
  padding-left: 20px;
}

.govuk-error-summary__list a {
  color: var(--govuk-red);
  font-weight: 700;
}

/* Summary list */
.govuk-summary-list {
  margin: 0 0 30px;
  padding: 0;
  border-top: 1px solid var(--govuk-mid-grey);
}

.govuk-summary-list__row {
  display: flex;
  gap: 20px;
  padding: 12px 0;
  border-bottom: 1px solid var(--govuk-mid-grey);
}

.govuk-summary-list__key {
  font-weight: 700;
  flex: 0 0 40%;
  margin: 0;
}

.govuk-summary-list__value {
  flex: 1;
  margin: 0;
}

.govuk-summary-list__actions {
  flex: 0 0 auto;
  margin: 0;
  text-align: right;
}

/* Confirmation panel */
.govuk-panel {
  margin-bottom: 30px;
  padding: 35px 25px;
  background: var(--govuk-green);
  color: #ffffff;
  text-align: center;
}

.govuk-panel__title {
  margin: 0;
  font-size: 32px;
  font-weight: 700;
}

/* Footer */
.govuk-footer {
  margin-top: 40px;
  padding: 25px 0;
  border-top: 1px solid var(--govuk-mid-grey);
  background: var(--govuk-light-grey);
}

.govuk-footer__text {
  margin: 0;
  font-size: 16px;
  color: var(--govuk-grey);
}
`

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
